## 자전거 대여 수요 예측
#### 2011년 1월부터 2012년 12월까지 날짜/시간, 기온, 습도, 풍속 등의 정보를 기반으로 1시간 간격 동안의 자전거 대여 횟수가 기재되어 있다.

- datetime: hourly date + timestamp
- season : 1=봄, 2=여름, 3=가을, 4=겨울
- holiday : 1=토,일요일의 주말을 제외한 국경일 등의 휴일, 0=휴일이 아닌 날
- workingday : 1=토,일요일의 주말 및 휴일이 아닌 주중, 0=주말 및 휴일
- weather:
 - 1=맑음, 약간 구름 낀 흐림
 - 2=안개, 안개+흐림
 - 3=가벼운 눈, 가벼운 비+천둥
 - 4=심한 눈/비, 천둥/번개
- temp : 온도 (섭씨)
- atemp : 체감온도 (섭씨)
- humidity : 상대습도
- windspeed : 풍속
- casual : 사전에 등록되지 않은 사용자가 대여한 횟수
- registered : 사전에 등록된 사용자가 대여한 횟수
- count : 대여 횟수

## 다음 코드는 복습과제를 하는데 있어 필요한 모듈입니다. 한 번 꼭 돌려주고 실습해 주세요.

In [45]:
import numpy as np
import pandas as pd
import seaborn as sns

In [46]:
import warnings
warnings.filterwarnings("ignore",category=RuntimeWarning)

## 1. 데이터 불러오기 및 전처리
### (1) bikeshare.csv를 pandas를 이용해 bike_df의 이름으로 저장하고 행렬 개수와 5개의 자료를 뽑아보시오.

In [54]:
bike_df=pd.read_csv('bikeshare.csv')
print(bike_df.shape)
print(bike_df.head())

(10886, 12)
              datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1  


### (2) bike_df에서 항목별 데이터 타입을 확인하는 코드를 작성하시오.

In [55]:
bike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   datetime    10886 non-null  object 
 1   season      10886 non-null  int64  
 2   holiday     10886 non-null  int64  
 3   workingday  10886 non-null  int64  
 4   weather     10886 non-null  int64  
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64  
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64  
 10  registered  10886 non-null  int64  
 11  count       10886 non-null  int64  
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB


### (3) pandas를 이용해 datetime의 칼럼을 년, 월, 일, 시간과 같은 4개의 속성으로 분리하시오.
- 판다스에서 문자열을 datatime 타입으로 변환하는 apply(pd.to_datetime) 메서드를 이용해 datetime이라는 이름의 새로운 칼럼을 만드시오.

In [56]:
bike_df["datetime"]=bike_df["datetime"].apply(pd.to_datetime)
bike_df.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0 2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1 2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2 2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3 2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4 2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

- apply() 함수와 lambda를 이용해 새로운 datetime 칼럼에서 년, 월, 일, 시간 칼럼을 새로 만드시오.

In [57]:
bike_df['year']=bike_df['datetime'].dt.year
bike_df['month']=bike_df['datetime'].dt.month
bike_df['day']=bike_df['datetime'].dt.day
bike_df['hour']=bike_df['datetime'].dt.hour

- 3개의 bike_df를 뽑아 제대로 칼럼들이 생성되었는지 확인하시오.

In [59]:
bike_df.head(3)

datetime  season  holiday  workingday  weather  temp   atemp  \
0 2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1 2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2 2011-01-01 02:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  year  month  day  hour  
0        81        0.0       3          13     16  2011      1    1     0  
1        80        0.0       8          32     40  2011      1    1     1  
2        80        0.0       5          27     32  2011      1    1     2

* datatime, causal, registered 칼럼을 삭제 하시오.(casual + registered = count이므로 따로 필요하지 않습니다.) 

In [60]:
bike_df.drop(['datetime','casual','registered'],axis=1,inplace=True)
bike_df.head()

season  holiday  workingday  weather  temp   atemp  humidity  windspeed  \
0       1        0           0        1  9.84  14.395        81        0.0   
1       1        0           0        1  9.02  13.635        80        0.0   
2       1        0           0        1  9.02  13.635        80        0.0   
3       1        0           0        1  9.84  14.395        75        0.0   
4       1        0           0        1  9.84  14.395        75        0.0   

   count  year  month  day  hour  
0     16  2011      1    1     0  
1     40  2011      1    1     1  
2     32  2011      1    1     2  
3     13  2011      1    1     3  
4      1  2011      1    1     4

## 2. 선형 회귀 실습하기

### (1) X_fearues와 y_target이라는 이름으로 독립변수와 종속변수를 분리하시오. (종속변수 = count)

In [61]:
X_features=bike_df.drop(['count'],axis=1)
y_target=bike_df['count']

### (2) 숫자형 카테고리 값을 pandas의 get_dummies를 이용해 원-핫 인코딩하시오.
- 현재 데이터타입이 숫자형 카테고리인 칼럼은 year,month,day,hour,holiday,workingday,season,weather 입니다.
- X_features_ohe란 이름에 저장하세요.

In [62]:
X_features_ohe= pd.get_dummies(bike_df, columns=['year','month','day','hour','holiday','workingday','season','weather'])

### (3) 사이킷런에서 train_test_split을 이용해 훈련세트와 테스트 세트를 분리하시오.
- 이때 종속변수는 count 칼럼이고 독립변수는 종속변수 이외의 모든 칼럼입니다.
- X_train,X_test,y_train,y_test 이란 이름으로 세트를 만들고 test_size=0.3,random_state=0 이라는 옵션 추가하세요.

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X_features_ohe,y_target, test_size=0.3,random_state=0)

### (4) 회귀 종류별로 실습

#### i. 선형 회귀
- 사이킷런에서 LinearRegression 을 불러와 fit한 후 X_test를 예측하여 pred란 이름에 저장하시오.
- 사이킷런에서의 mean_square_error과 np.sqrt()를 이용해 y_test와 pred의 RMSE를 출력하시오.
- 이 모델의 intercept와 coefficient를 출력하시오.

In [74]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

pred=lin_reg.predict(X_test)

In [79]:
np.sqrt(mean_squared_error(y_test,pred))

9.702910858819243e-14

In [80]:
lin_reg.intercept_, lin_reg.coef_

(-0.0009396688719789381,
 array([ 2.69340971e-15,  4.66293670e-15, -9.71445147e-16,  2.40085729e-15,
         1.00000000e+00, -1.58636460e-04, -1.58636460e-04,  1.02068294e-03,
         1.02068294e-03,  1.02068294e-03, -5.42289651e-05, -5.42289651e-05,
        -5.42289651e-05,  6.37740041e-05,  6.37740041e-05,  6.37740041e-05,
         4.38270350e-04,  4.38270350e-04,  4.38270350e-04,  3.64551858e-05,
         3.64551858e-05,  3.64551858e-05,  3.64551858e-05,  3.64551858e-05,
         3.64551858e-05,  3.64551858e-05,  3.64551858e-05,  3.64551858e-05,
         3.64551858e-05,  3.64551858e-05,  3.64551858e-05,  3.64551858e-05,
         3.64551858e-05,  3.64551858e-05,  3.64551858e-05,  3.64551858e-05,
         3.64551858e-05,  3.64551858e-05, -2.73233489e-06, -2.73233489e-06,
        -2.73233489e-06, -2.73233489e-06, -2.73233489e-06, -2.73233489e-06,
        -2.73233489e-06, -2.73233489e-06, -2.73233489e-06, -2.73233489e-06,
        -2.73233489e-06, -2.73233489e-06, -2.73233489e-06, -2.7

#### ii. 확률적 경사 하강법을 이용한 선형 회귀
- 사이킷런에서 제공하는 SGDRegressor을 이용해 위와 같은 과정을 반복하시오.
- 이때 max_iter=1000,tol=1e-3,penalty=None,eta0=0.1 인 옵션을 추가하시오.

In [81]:
from sklearn.linear_model import SGDRegressor

sgd_reg=SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=0.1)
sgd_reg.fit(X_train, y_train)

pred_sgd=sgd_reg.predict(X_test)

In [83]:
np.sqrt(mean_squared_error(y_test,pred_sgd))

74724700193810.92

In [84]:
sgd_reg.intercept_, sgd_reg.coef_

(array([-6.99838847e+10]),
 array([ 1.23188888e+11,  5.58164217e+11,  7.94569195e+11,  1.33461128e+11,
         3.17574887e+10, -2.20424185e+11,  1.50440300e+11, -9.90662343e+10,
         2.86345221e+11,  1.03119223e+11, -1.17175816e+11,  2.49011740e+11,
        -2.41862234e+11,  2.72426652e+11,  1.03005537e+11, -2.63146639e+11,
        -3.32949337e+11, -6.70805324e+10,  3.73885342e+10, -2.67631156e+11,
        -4.46371152e+10,  2.34920678e+11, -2.24294350e+10,  4.28448011e+10,
        -8.65732003e+10, -3.01264913e+11, -1.33015869e+11,  1.67310292e+11,
        -1.54383245e+11, -3.42416996e+11,  5.59514936e+11,  1.78298246e+11,
         5.62787068e+10, -1.03536257e+11,  1.18474648e+11,  2.52393431e+11,
        -1.87912741e+11, -3.62186966e+10,  5.51309727e+10, -4.95463383e+11,
        -5.19410805e+11,  1.17707052e+11, -1.69510148e+11,  2.04782881e+11,
        -1.24158249e+11,  3.84709504e+11,  7.79446462e+11, -5.56851008e+11,
         6.35915916e+11, -1.28172381e+12,  4.66068173e+11, -7

#### iv. 라쏘와 릿지
- 위와 같은 방식대로 사이킷런에서 Ridge와 Lasso를 불러와 RMSE를 출력하시오.
- 각각의 intercept, coefficient를 출력하시오.
- Ridge와 Lasso에서 alpha=0.1 이라는 옵션을 추가하시오.

In [88]:
from sklearn.linear_model import Ridge, Lasso

ridge_reg = Ridge(alpha=0.1)
ridge_reg.fit(X_train, y_train)
pred_ridge=ridge_reg.predict(X_test)

In [89]:
np.sqrt(mean_squared_error(y_test,pred_ridge))

1.3425271362351556e-07

In [94]:
ridge_reg.intercept_, ridge_reg.coef_

(1.2329252285780967e-07,
 array([ 3.66814667e-09,  2.45233634e-09, -1.06330736e-09, -9.68073501e-10,
         9.99999999e-01, -5.68548542e-08,  5.68548542e-08, -3.66139438e-08,
        -1.46409814e-08,  8.30343300e-09, -1.31072420e-08,  2.01756891e-08,
         3.92569490e-09, -1.38517251e-08, -1.27841273e-08,  3.30561525e-08,
         2.94361280e-08,  3.78275359e-10, -1.41357595e-09, -1.29581147e-08,
        -3.72942957e-09,  1.71364868e-09,  1.14217293e-09,  2.88659831e-09,
         5.55757485e-10, -1.00730894e-08, -1.26002482e-08,  8.98655563e-11,
         1.35155007e-09,  2.73812159e-09, -6.70150796e-09,  2.81703311e-09,
         3.70932875e-09,  8.90461317e-09,  2.90971174e-09,  2.39717850e-08,
        -8.37783197e-09,  1.55677444e-09, -1.64795939e-07, -1.92220509e-07,
        -2.10468832e-07, -2.19762877e-07, -2.22160747e-07, -1.97658482e-07,
        -1.24619453e-07,  5.35599868e-08,  2.54870723e-07,  5.39406053e-08,
        -2.20068895e-08,  7.27069462e-09,  6.89436244e-08,  6.2

In [93]:
lasso_reg=Lasso(alpha=0.1)
lasso_reg.fit(X_train,y_train)
pred_lasso=lasso_reg.predict([X_test]) #오류 해결 어떻게 해야 하나요...?ㅜ

ValueError: cannot copy sequence with size 3266 to array axis with dimension 74

In [96]:
np.sqrt(mean_squared_error(y_test,pred_lasso))

NameError: name 'pred_lasso' is not defined

In [95]:
lasso_reg.intercept_, lasso_reg.coef_

(0.0005777093964525193,
 array([ 0.        ,  0.        , -0.        ,  0.        ,  0.99999697,
        -0.        ,  0.        , -0.        , -0.        , -0.        ,
        -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , -0.        , -0.        ,
        -0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        -0.        , -0.        , -0.        ,  0.        ,  0.        ,
        -0.        ,  0.        ,  0.        ,  0.        , -0.        ,
         0.        ,  0.        ,  0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ,
         0.        ,  0.        ,  0.        , -0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.        ,
        -0.        , -0.        ,  0.        , -0.        , -0.        ,
         0.        , -0.   

## 3. 로지스틱 회귀 분석 실습 _ 와인 종류 분류하기 : 와인의 화학 조성을 사용하여 와인의 종류를 예측하기 위한 데이터이다. 

In [97]:
# 와인 데이터를 불러오기 위한 코드입니다. 꼭 실행해주세요.
from sklearn import datasets

ㅇ 타겟 데이터 : 와인의 종류 0, 1, 2의 세가지 값

ㅇ 특징 데이터

* 알콜(Alcohol)

* 말산(Malic acid)

* 회분(Ash)

* 회분의 알칼리도(Alcalinity of ash)

* 마그네슘(Magnesium)

* 총 폴리페놀(Total phenols)

* 플라보노이드 폴리페놀(Flavanoids)

* 비 플라보노이드 폴리페놀(Nonflavanoid phenols)

* 프로안토시아닌(Proanthocyanins)

* 색상의 강도(Color intensity)

* 색상(Hue)

* 희석 와인의 OD280/OD315 비율 (OD280/OD315 of diluted wines)

* 프롤린(Proline)

####3-1. 와인 데이터 가져오기 

In [101]:
wine_data = datasets.load_wine()

더 자세한 데이터에 대한 설명을 보고싶으시다면 아래의 코드를 실행해주시면 됩니다. 

In [99]:
print(wine_data.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

#### 3-2. 입력변수와 목표변수 설정하기
* 입력변수를 사용하기 편하게 pandas dataframe으로 변환해주세요.
  - 입력변수는 data (.data) 함수를 써서 가져오시면 됩니다.
  - 칼럼명 가져오기 : .feature_names 
* 목표변수를 사용하기 편하게 pandas dataframe으로 변환해주세요
  - 목표변수는 target (.target) 함수를 써서 가져요오시면 됩니다. 
  - 칼럼명은 'target'으로 지정해주세요

In [109]:
# 입력 변수를 사용하기 편하게 pandas dataframe으로 변환
X = pd.DataFrame(wine_data.data,columns=[wine_data.feature_names])
# 목표 변수를 사용하기 편하게 pandas dataframe으로 변환
y =pd.DataFrame(wine_data.target,columns=['target'])

target
0         0
1         0
2         0
3         0
4         0
..      ...
173       2
174       2
175       2
176       2
177       2

[178 rows x 1 columns]

#### 3-3. 훈련 데이터, 테스트 데이터 만들기
* train_test_split 함수를 사용해 테스트 셋의 비율이 0.2가 되도록 X_train, X_test, y_train, y_test 을 만들어주세요. random_state=5로 설정해주세요.
* 경고메세지를 없애도록 y_train = y_train.values.ravel() 를 실행해주세요

In [110]:
X_train, X_test, y_train, y_test= train_test_split(X_features_ohe,y_target, test_size=0.3,random_state=5)

y_train = y_train.values.ravel()

#### 3-4. 모델훈련
* 로지스틱회귀 함수에서 옵션을 solver='saga', max_iter=7500으로 설정해주세요.
* 학습데이터로 모델을 학습시켜주세요

In [ ]:
# 필요한 라이브러리 import
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver="saga", max_iter=7500)
log_reg.fit(X_train, y_train)

#### 3-5. 예측
* 테스트 데이터 셋으로 로지스틱 회귀 모델을 이용해 와인 데이터 분류를 예측해 결과를 y_test_predict 변수에 담아주세요
* score함수를 사용해 로지스틱 회귀 모델의 성능을 score 변수에 담아주세요
* y_test_predict와 score 결과를 확인해주세요.

In [ ]:
# 로지스틱 회귀 모델를 이용해서 각 와인 데이터 분류를 예측함
y_test_predict=log_reg.predict(X_test)

# 로지스틱 회귀 모델의 성능 확인 (정확성 %를 리턴함)
score=logit_reg.score(X_train, y_train)
# 결과확인 
y_test_predict, score

#### (선택) 3-6. GridSearchCV 복습

`LogisticRegression` 모델에 `param_grid`를 사용하여 GridSearchCV를 진행해주세요.
- cv = 5
- 추가적으로 코드를 작성하실 필요 없이, 골뱅이@@@ 부분의 코드를 완성해서 출력해주시면 됩니다. 

In [ ]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import GridSearchCV

# param_grid (수정하셔도 됩니다)
params = {
    'penalty':['l1', 'l2', 'elasticnet'],        # l1 is Lasso, l2 is Ridge
    'C': np.linspace(0.00002,1,100)
}

# GridSearch
grid_search = GridSearchCV(LogisticRegression, param_grid='accuracy', cv=5)
grid_search.fit(X_train, y_train)

학습된 gridsearch 모델에 저장되어 있는 best parameter, best score 를 출력해주세요.

In [ ]:
grid_search.best_params_, grid_search.best_score_